dist: bionic
language: c

git:
  depth: false # needed to get common ancestor to master

addons:
  apt:
    update: true
    packages:
    - gawk
    - wget
    - git-core
    - diffstat
    - unzip
    - texinfo
    - gcc-multilib
    - build-essential
    - chrpath
    - socat
    - cpio
    - python
    - python3
    - python3-pip
    - python3-pexpect
    - xz-utils
    - debianutils
    - iputils-ping
    - libsdl1.2-dev
    - xterm



stages:
  - compile

env:
  global:
  - DISTRO="poky-freertos"
  - SSTATE_MIRRORS="file://.* http://sstate.yoctoproject.org/2.99/PATH;downloadfilename=PATH"
  matrix:
  - MACHINE="qemuarmv5"

script:
  - cd ..
  - git clone git://git.yoctoproject.org/poky
  - cd poky
  - source oe-init-build-env
  - echo "MACHINE = \"${MACHINE}\"" >> ./conf/local.conf
  - echo "DISTRO = \"${DISTRO}\"" >> ./conf/local.conf
  - echo "SSTATE_MIRRORS = \"${SSTATE_MIRRORS}\"" >> ./conf/local.conf
  - bitbake-layers add-layer ../../meta-freertos
  - bitbake freertos-demo