# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: myJob
  timeoutInMinutes: 2

  trigger:
  - master

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    DISTRO: 'poky-freertos'
    SSTATE_MIRRORS: 'file://.* http://sstate.yoctoproject.org/2.99/PATH;downloadfilename=PATH;downloadfilename=PATH'
    MACHINE: 'qemuarmv5'


  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - bash: |                                                                                                                   
      sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
      build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
      xz-utils debianutils iputils-ping libsdl1.2-dev xterm
      cd                                                                                                                 
      git clone git://git.yoctoproject.org/poky                                                                             
      cd poky
      git clone https://github.com/aehs29/meta-freertos.git                                                                                                      
      source oe-init-build-env                                                                                              
      echo "MACHINE = \"${MACHINE}\"" >> ./conf/local.conf                                                                  
      echo "DISTRO = \"${DISTRO}\"" >> ./conf/local.conf                                                                    
      echo "SSTATE_MIRRORS = \"${SSTATE_MIRRORS}\"" >> ./conf/local.conf                                                    
        bitbake-layers add-layer ../meta-freertos                                                                          
      bitbake freertos-demo-local
    displayName: 'Run a multi-line script'