trigger:
- master
- zeus
- warrrior

schedules:
- cron: "0 0 * * *"
  displayName: Weekly Sunday build
  branches:
    include:
    - releases/*
  always: true


jobs:
- job: FreeRTOSJob
  timeoutInMinutes: 0

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    DISTRO: 'poky-freertos'
    #SSTATE_MIRRORS: 'file://.* http://sstate.yoctoproject.org/2.99/PATH;downloadfilename=PATH;downloadfilename=PATH'
    MACHINE: 'qemuarmv5'

  steps:
  - bash: |
      echo Building FreeRTOS $PWD
      ls -l
    displayName: 'echoInit'

  - bash: |                                                                                                                   
      # Install dependencies
      echo "Installing dependencies"
      sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
      build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
      xz-utils debianutils iputils-ping libsdl1.2-dev xterm
    displayName: 'Installing Dependencies'

  - bash: |
      # Pull Repositories
      cd ~/
      echo "Cloning Yocto Project"
      git clone git://git.yoctoproject.org/poky -b $(Build.SourceBranchName)                                                                    
      cd poky
      #echo "Cloning meta-freertos"                                                                                                                 
      #git clone https://github.com/aehs29/meta-freertos.git
    displayName: 'Cloning Repositories'
      
  - bash: |
      # Add layers and create local.conf                                                                                  
      source oe-init-build-env                                                                                              
      echo "MACHINE = \"${MACHINE}\"" >> ./conf/local.conf                                                                  
      echo "DISTRO = \"${DISTRO}\"" >> ./conf/local.conf                                                                    
      echo "SSTATE_MIRRORS = \"${SSTATE_MIRRORS}\"" >> ./conf/local.conf                                                    
      bitbake-layers add-layer $(Build.SourcesDirectory)/meta-freertos
    displayName: 'Create configuration'

  - bash: |
      # Build
      echo "Building sample demo (local)"                                                                          
      bitbake freertos-demo-local -k
    displayName: 'Build FreeRTOS local demo'

  - bash: |
      # Build
      echo "Building sample demo"                                                                          
      bitbake freertos-demo -k
    displayName: 'Build FreeRTOS demo'